args: !!python/object:argparse.Namespace
  architecture: LLaMa
  batch_size: 32
  custom_cross_entropy: 'false'
  d_ff_mult: 4
  d_model: 512
  dataset: wikitext2
  dropout: 0.1
  extra_descriptor: ''
  groups: 8
  lr: 0.0004
  lr_mult: 0.5
  nhead: 8
  num_layers: 6
  orthograd: true
  seed: 42
  seq_len: 128
  t_0: 45000
  t_mult: 1.5
  t_total: 50000
  type: test
  use_character_encoding: true
  v1: true
  warmup_steps: 5000
batch_size: 32
cce_fn: 'false'
learning_rate: 0.0004
lr_mult: 0.5
t_0: 50000
t_mult: 1.5
vocab_size: 281
warmup_steps: 5000
