args: !!python/object:argparse.Namespace
  architecture: Dint
  batch_size: 32
  custom_cross_entropy: 'false'
  d_ff_mult: 4
  d_model: 512
  dropout: 0.1
  extra_descriptor: v1_no_orthograd
  groups: 4
  lr: 0.0002
  lr_mult: 0.5
  nhead: 8
  num_layers: 6
  orthograd: true
  seed: 42
  seq_len: 128
  t_0: 45000
  t_mult: 1.5
  t_total: 15000
  type: test
  v1: true
  warmup_steps: 5000
batch_size: 32
cce_fn: 'false'
learning_rate: 0.0002
lr_mult: 0.5
t_0: 50000
t_mult: 1.5
vocab_size: 65
warmup_steps: 5000
