args: !!python/object:argparse.Namespace
  architecture: Money_former
  batch_size: 16
  config: ./experiment_configs/Money_test.json
  d_ff: 512
  d_model: 128
  dataset: Money
  dropout: 0.1
  dtype: fp32
  experiment_notes: added attention sink/seperator tocken? emas ppo macd (3 volitilities,
    ADR, 2 ATR, 3 SMA,3 SMAR, 3 volitilities returns 3(6) bollinger bands, removed
    adj close, now predicting close)
  extra_descriptor: dw2w_OCCHLVv_returns_hella_features_indicators
  indices_to_predict:
  - 1
  - 5
  - 10
  input_features: 31
  lr: 0.00015
  lr_mult: 0.5
  nhead: 4
  num_layers: 4
  num_params: 1060995
  orthograd: true
  predict_gaussian: false
  qk_rope_dim: 32
  seq_len: 64
  t_0: 9000
  t_mult: 1.5
  t_total: 50000
  tickers:
  - AAPL
  type: test
  warmup_steps: 1000
batch_size: 16
learning_rate: 0.00015
lr_mult: 0.5
normalized_threshold: 0.1
t_0: 10000
t_mult: 1.5
warmup_steps: 1000
